export const createTypography = () => ({
  fontFamily:
    '"Playfair Display", "Josefin Sans","Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
  body1: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontSize: "1rem",
    fontWeight: 400,
    lineHeight: 1.5,
  },
  body2: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontSize: "0.875rem",
    fontWeight: 400,
    lineHeight: 1.57,
  },
  button: {
    fontWeight: 600,
  },
  caption: {
    fontSize: "0.75rem",
    fontWeight: 500,
    lineHeight: 1.66,
  },
  subtitle1: {
    fontSize: "1rem",
    fontWeight: 500,
    lineHeight: 1.57,
  },
  subtitle2: {
    fontSize: "0.875rem",
    fontWeight: 500,
    lineHeight: 1.57,
  },
  overline: {
    fontSize: "0.75rem",
    fontWeight: 600,
    letterSpacing: "0.5px",
    lineHeight: 2.5,
    textTransform: "uppercase",
  },
  h1: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    lineHeight: "28px",
    fontSize: "39px",
  },
  h2: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: "25px",
    lineHeight: "59.48px",
  },
  h3: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: "25px",
    lineHeight: "30px",
  },
  h4: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: "20px",
    lineHeight: "38.13px",
  },
  h5: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "30px",
  },
  h6: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: "14px",
    lineHeight: "24.4px",
  },
  h7: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: "10px",
    lineHeight: "19.83px",
  },
  h8: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: "8px",
    lineHeight: "15.25px",
  },
  p1: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontWeight: 400,
    fontSize: "39px",
    lineHeight: 1.5,
  },
  p2: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontWeight: 400,
    fontSize: "31px",
    lineHeight: 1.5,
  },
  p3: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontWeight: 400,
    fontSize: "25px",
    lineHeight: 1.5,
  },
  p4: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontWeight: 400,
    fontSize: "20px",
    lineHeight: 1.5,
  },
  p5: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: 1.5,
  },
  p6: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: 1.5,
  },
  p7: {
    fontFamily: "'Josefin Sans', sans-serif",
    fontWeight: 400,
    fontSize: "10px",
    lineHeight: 1.5,
  },
});
