

import "./globals.css";
import Header from "./layouts/header/Header";
import Footer from "./layouts/footer/Footer";
import AppProviders from "@components/global/provider/AppProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
        <Header/>
        <ToastContainer />
      {children}
      <Footer/>
        </AppProviders>

      </body>
    </html>
  );
}
